image: index.docker.io/gesquive/go-builder:latest

variables:
  GOPATH: ${CI_PROJECT_DIR}/vendor/go
  LOCAL_BIN: bin

.modcache: &modcache
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - vendor/go/pkg/mod
    - bin
  policy: pull

before_script:
  - make deps

stages:
  - deps
  - test
  - build
  - release

dependencies:
  stage: deps
  script:
    - make deps
  cache:
    <<: *modcache
    policy: pull-push

unit_tests:
  stage: test
  script:
    - make test
  cache:
    <<: *modcache

.race_detector:
  stage: test
  script:
    - make race
  cache:
    <<: *modcache

code_coverage:
  stage: test
  coverage: '/coverage: \d+.\d+% of statements/'
  script:
    - make coverage
  cache:
    <<: *modcache

build:
  stage: build
  script:
    - make
  cache:
    <<: *modcache

pages:
  stage: release
  script:
    - make coverage-report
    - mv coverage/ public/
  cache:
    <<: *modcache
  artifacts:
    paths:
      - public
  only:
    - master

release-dev:
  stage: release
  script:
    - make local-release
  cache:
    <<: *modcache
  environment:
    name: development
  artifacts:
    paths:
      - dist/*_v*.tar.gz
      - dist/*_v*.zip

release-prod:
  stage: release
  script:
    - make release
  cache:
    <<: *modcache
  environment:
    name: production
  artifacts:
    paths:
      - dist/*_v*.tar.gz
      - dist/*_v*.zip
  when: manual
  only:
    - tags
