image: golang:1.12.5

.cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - /go

stages:
  - test
  - build
  - deploy

before_script:
  - make deps

unit_tests:
  stage: test
  script:
    - make test

race_detector:
  stage: test
  script:
    - make race

code_coverage:
  stage: test
  script:
    - make coverage
  coverage: '/coverage: \d+.\d+% of statements/'

build:
  stage: build
  script:
    - make

pages:
  stage: deploy
  script:
    - make coverage-report
    - mv coverage/ public/
  artifacts:
    paths:
      - public
  only:
    - master

deploy-dev:
  stage: deploy
  script:
    - make dist
  environment:
    name: development
  artifacts:
    paths:
      - dist/*-v*.tar.gz
      - dist/*-v*.zip
  only:
    - tags

deploy-prod:
  stage: deploy
  script:
    - make dist
  environment:
    name: production
  artifacts:
    paths:
      - dist/*-v*.tar.gz
      - dist/*-v*.zip
  when: manual
  only:
    - tags
