image: golang:1.10.3

.cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - vendor/

stages:
  - test
  - build
  - deploy

before_script:
  - make link
  - pushd $(make path)
  - make deps

unit-tests:
  stage: test
  script:
    - make test

race-detector:
  stage: test
  script:
    - make race

code-coverage:
  stage: test
  script:
    - make cover

build:
  stage: build
  script:
    - make

deploy-dev:
  stage: deploy
  script:
    - make dist
  environment:
    name: development
  artifacts:
    paths:
      - dist/*-v*.tar.gz
      - dist/*-v*.zip
  only:
    - tags

deploy-prod:
  stage: deploy
  script:
    - make dist
  environment:
    name: production
  artifacts:
    paths:
      - dist/*-v*.tar.gz
      - dist/*-v*.zip
  when: manual
  only:
    - tags
