language: go
go:
- 1.12.x
install: make deps
script: make
before_deploy: make dist
deploy:
  provider: releases
  api_key:
    secure: tUZVhdayx5gENzh6u2qaqhXyo4GyI8IoIC0L3qrAKTSMXboUl0p07w//JkJi9rCiyKE6YB45h8AoppB9chnrEFtZOjpOApSGUYV8PEqUFmCxlmpF9+sUHJUY9+Yt5/7wMqL40Y5gwGXDmJojGnvHczkYMPz2MqvGoYvGBFXJXJrqD7115mi5grk+DH+rD6eyM7wXG4cdCkc6vwYHpkcx1h/I3PiltlYfEA0EZhfbPk6nE0ZSNeJdKr9TTH/qbuYNjEkGDwP8wBuLaVJ6Wx4QbCj6iUjPRagqa9lDT14+6GMkXYAYbB2yEjCte0C5AMUk5S7HkMfEKeoC2PECVUYoSoMnTQ2vHUMePIGrOX1CvgMAYMMESp5eWEO+7AdnQl1KzZ6lX+2qY9slLeae+Flx+DbrvNZdJcWHWWB6xM49/u9ljbzbaTII1pmQmPJb5kzQ4fbADGrEw73xufwFcG8G05Kbq8WeT5E+94NAah1KalEilzjyWtqbc22gwlcLYCN34AgB02EdQMljI/l6jFZJ5Yi5FIIw1z2go5VFuQlXUmZ1PFe+QDqKXnlthoMezxCxfHEoQO9Ts1yqO4op6cnJCn7ZeGzM771caE8iHksFrW4XVjvzSak8nhXAzKDIqcIQmCfEiPgcGUKWo9NzC8AowxvcaOv/g1S3KY7apOWMYeQ=
  file_glob: true
  file:
    - dist/*-v*.tar.gz
    - dist/*-v*.zip
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+(\.[0-9]+)?(-[^ \t\r\n\v\f]*)?$ && $TRAVIS_GO_VERSION =~ ^1\.12\.?[0-9x]*$
