
version: 2
jobs:
  build:
    docker:
      - image: gesquive/go-builder:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run: make deps
      - run: make test
      - run: make
      - save_cache:
          key: source-v1-< .Revision >
          paths:
            - dist
            - vendor

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
