.nh
.TH GHOST(1)May 2020
ghost
ghost utils
.SH NAME
.PP
ghost \- This app is transient and does nothing
.SH SYNOPSIS
.PP
\fBghost [flags]\fP
.SH DESCRIPTION
.PP
This app is transient and does nothing, all you see is the faint
outline of an application
.SH OPTIONS
.PP
\fB\-\-config\fP=""
	Path to a specific config file (default "./config.yml")
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for ghost
.PP
\fB\-o\fP, \fB\-\-run\-once\fP[=false]
	Only run once and exit
.PP
\fB\-\-version\fP[=false]
	Display the version number and exit
